require "rake/clean"

MAINDOC = %w[../README.md]

CLEAN.include "../md/[0-9]*/image"
CLEAN.include "../md/[0-9]*/README.md"
CLEAN.include MAINDOC
CLEAN.include "*.tmp"
CLEAN.include %w[soundfit.par fit.log]

SRC = FileList["[0-9]*.rb"]
IMG = SRC.pathmap("../md/%n/image")
DOC = SRC.pathmap("../md/%n/README.md")

file "../README.md" => IMG do |t|
  sh "ruby mkmd.rb"
end

rule /\/image$/ => "%-1d.rb" do |t|
  sh "ruby #{t.source}"
end

task :default => MAINDOC
